default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV["DB_POOL"] || 5  %>
  database: <%= ENV['DB_NAME'] || 'demo_development' %>
  username: <%= ENV['DB_USER'] || 'demo' %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV["DB_HOST"] || '127.0.0.1' %>
  url: <%= ENV['DATABASE_URL'] %> # takes higher precedence than other settings
  reconnect: true

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'demo_development' %>

test:
  <<: *default
  database: demo_test

production:
  <<: *default
  database: demo_production
  url: <%= ENV['DATABASE_URL'] %>
